title: Zhuowei Zhang
email: zhuoweiz@usc.edu
description: >- # this means to ignore newlines until "baseurl:"
  Zhuowei Zhang personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DoitogetherO
github_username:  zhuoweiz

# theme: jekyll-theme-cayman
theme: minima
plugins:
  - jekyll-feed
